### ISSUE TITLE
Usability : Cannot paste URL from clipboard into "Enter URL"

### ISSUE THREAD

**Issue by olivier-fs** [BKSalman/ytdlp-gui#7] opened 2022-11-14 15:49 UTC
Hi!
Just tried ytdlp-gui, works great!

But I can't copy/paste an URL from the clipboard into the "Enter URL" text input.

ytdlp-gui : version: v0.2.0, prebuilt, from Releases /  ytdlp-gui-windows-64.zip.
Platform : Windows 10.

I've read issue #2 "TODOs" and I don't see "Add clipboard handling".
I'm not sure if it's a bug on the Windows platform only, or if clipboard handling is not implemented (at all by iced, or just in ytdlp-gui.

So I classify this issue as "usability", not "bug".

**Comment by BKSalman** [comment] 2022-11-18 12:17
Hello!

sorry for the late reply!

this issue is not present on linux, as I personally use the app, so I think it's a bug within iced or something else,

I will contact the iced team about this issue!

**Comment by BKSalman** [comment] 2022-11-18 12:41
I couldn't reproduce the same issue in my windows 10 VM, 

I don't have a way to log clipboard events and such,

but I will check if someone else can reproduce it

**Comment by olivier-fs** [comment] 2022-11-18 14:26
Hi!
I just tried with latest git pull of iced, running the examples/todos example, and... copy/paste doesn't work !
Neither copy from the todos input, nor pasting into the input.

I have two linux boxes, one Gentoo and one Arch. I'll try on these later, but you already confirmed that's ok for you (obvious, you wouldn't have released otherwise).

So it is a platform specific problem. I can't guess why it's ok on some W10 and KO on another... Maybe someone else on W10 can confirm ? In this case we could open an issue on the official iced repo.

BTW great choice with iced ! I think it's gonna be much better than gtk-rs or others (qt, etc.) bindings to cpp. (moreover on non-linux paltforms). System76 is working on it's own fork of iced for their upcoming Pop_OS! Cosmic Desktop. They are adding tons of features :multiline support, full UTF-8 / i18n support, etc :-]

**Comment by BKSalman** [comment] 2022-11-18 18:41
> So it is a platform specific problem. I can't guess why it's ok on some W10 and KO on another... Maybe someone else on W10 can confirm ? In this case we could open an issue on the official iced repo.

agree, you can open the issue since I can't reproduce it on my machine :p 

> BTW great choice with iced ! I think it's gonna be much better than gtk-rs or others (qt, etc.) bindings to cpp. (moreover on non-linux paltforms). System76 is working on it's own fork of iced for their upcoming Pop_OS! Cosmic Desktop. They are adding tons of features :multiline support, full UTF-8 / i18n support, etc :-]

Hell yeah! I'm in the iced discord and I see the progress they're making with system76 and it's really cool to witness, also iced is really nice to work with and will get so many exciting features in the future as you mentioned :]

I will close this issue since it's not related to this project, thanks for reporting tho!

**Closed by BKSalman** 2022-11-18 18:41 UTC
Labels: bug
